[package]
name = "bowling-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.35"
crossterm = "0.27.0"
dotenvy = "0.15.7"
itertools = "0.12.1"
ratatui = "0.26.1"
serde = "1.0.197"
tui-input = "0.8.0"

[dependencies.mongodb]
version = "2.8.2"
features = ["tokio-sync"]
