[package]
name = "bt-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bt-base = { path = "../bt-base" }
bt-util = { path = "../bt-util" }
dotenv = "0.15.0"
chrono = "0.4.31"
